### PR TITLE
Update to RELEASE121

### PR DESCRIPTION
**Pull request by jglick**
Without exclusions, build fails with

```
Generating Auto Update information for org.openide.modules
Some included modules/bundles depend on these codenamebases but they are not included. The application will fail starting up. The missing codenamebases are:
   org.netbeans.modules.javascript.nodejs          ref: [org.netbeans.modules.debugger.jpda.trufflenode]
   org.netbeans.libs.graaljs          ref: [org.netbeans.modules.nashorn.execution]
   org.netbeans.libs.truffleapi          ref: [org.netbeans.modules.nashorn.execution, org.netbeans.modules.debugger.jpda.truffle]
Some tokens required by included modules are not provided by included modules. The application will fail starting up. The missing tokens are:
   org.netbeans.modules.web.browser.api.PageInspector          ref: [org.netbeans.modules.ko4j.debugging]
   org.netbeans.modules.nbjavac          ref: [org.netbeans.modules.java.source.nbjavac]
```

Can work around that only by manually excluding those modules plus their transitive dependency closure.

### CODE REVIEW

**Comment by jglick** [comment]
For the build error, @JaroslavTulach suggests simply excluding all the problematic modules. Need to look up how to do that. I did not deliberately _include_ them, they just get added as part of the entire cluster.

The test error is still TBD. Likely need to figure out how to use JDK 11’s implementation in the test classpath. Of course if I can do that I can probably compile against it as well. Familiar with the `system`-scope hack used for older JDKs but not offhand how to do this with the modularized JDK.

**Comment by jglick** [comment]
So now `ApplicationTest` is failing. There are a lot of warnings about modules that could not be installed, but those are not treated as fatal. But then there are lots of stack traces too, like

```
SEVERE [org.netbeans.modules.netbinox]: framework event org.eclipse.mylyn.wikitext.core type 2
org.osgi.framework.BundleException: The bundle "org.eclipse.mylyn.wikitext.core_2.6.0.v20150901-2143 [95]" could not be resolved. Reason: Missing Constraint: Require-Bundle: com.google.guava; bundle-version="15.0.0"
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.getResolverError(AbstractBundle.java:1332)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.getResolutionFailureException(AbstractBundle.java:1316)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:323)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1184)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at org.eclipse.osgi.framework.internal.core.EquinoxLauncher.internalStart(EquinoxLauncher.java:271)
	at org.eclipse.osgi.framework.internal.core.EquinoxLauncher.start(EquinoxLauncher.java:241)
	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:258)
	at org.netbeans.core.netigso.Netigso.start(Netigso.java:183)
	at org.netbeans.NetigsoHandle.startFramework(NetigsoHandle.java:188)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1450)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1254)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:315)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:251)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:298)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:156)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:125)
	at org.netbeans.core.startup.Main.start(Main.java:282)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
[catch] at java.lang.Thread.run(Thread.java:748)
```

So first of all, where is this `com.google.guava` module supposed to be coming from? Also visible from regular module deps:

```
org.netbeans.modules.lsp.client - The module named com.google.guava was needed and not found.
```

And second of all, why does this merit a stack trace? We already got a polite warning

```
Warning - could not install some modules:
	org.eclipse.mylyn.wikitext.core - org.netbeans.InvalidException: Netigso: …/application/target/nb/ide/modules/org-eclipse-mylyn-wikitext-core.jar: Cannot start org.eclipse.mylyn.wikitext.core state remains INSTALLED after start()
```

Seems like a bug in the NB module system that it printing a stack trace for this condition.

**Comment by jglick** [comment]
So `ide-RELEASE121.pom` does specify

```xml
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>27.0-jre</version>
      <classifier></classifier>
    </dependency>
```

yet there is no trace of this in `application/target/`. In a real NB installation I see `ide/modules/com-google-guava.jar` along with `ide/config/Modules/com-google-guava.xml` and `ide/update_tracking/com-google-guava.xml`. So I am left to conclude that the `cluster-app` mojo does not support Netigso.

**Comment by jglick** [comment]
Seems I was using an outdated version of `nbm-maven-plugin`. Trying to fix that now.

**Comment by jtulach** [comment]
Hello Jesse & others affected by [Oracle NetBeans Nexus](http://137.254.56.27/maven2/). being down. I have a backup of the repository and I've just made it [available to public](http://netbeans.apidesign.org):
```
@@ -90,7 +90,7 @@
       <repository>
           <id>netbeans</id>
           <name>NetBeans</name>
-          <url>http://bits.netbeans.org/maven2/</url>
+          <url>http://netbeans.apidesign.org/maven2/</url>
       </repository>
   </repositories>
   <build>
```
is the fix to get `RELEASE82` and older bits from [my site](http://netbeans.apidesign.org). That's just for completeness. Of course, updating to `RELEASE121` is a better choice.

**Comment by jglick** [comment]
Thanks for the update—that could be very helpful to buy time while figuring out how to update.

**Comment by JaroslavTulach** [comment]
Chicken & egg problem: your report made me expose my backup to public. Hopefully others can benefit.

**Pull request merged**
